import "../styles/globals.css";
import "../styles/mdb.min.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Script from "next/script";
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>OpenContest</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Component {...pageProps} />

      <Script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.js"
      ></Script>
    </>
  );
}

export default MyApp;
